name: Test Ant

on:
  workflow_dispatch:
  push:
    branches:
      - stabilizeant

permissions: {}
jobs:
  build:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: test ant
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Check Maven Cache
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.x'
      - name: Set up JDK 11
        id: jdk-11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 6.0.2
      - name: run tests
        id: build-snapshot
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
          mvn -V -s settings.xml --no-transfer-progress --batch-mode -pl ant -am verify
      